org.gradle.jvmargs=-Xmx2048m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

#The following properties where added from the android gradle plugin, and will be removed from this file in a future version.
android.nonTransitiveRClass=true
android.useAndroidX=true
constraintlayout.version=2.2.0
